version: "3.9"
services:
  web:
    build: .
    command: ./bin/rails s -b 0.0.0.0 -p 3000
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
