version: "3.9"
services:
  web:
    build: .
    container_name: rails-web
    command:  bash -c "rm -f tmp/pids/server.pid && ./bin/rails db:prepare && ./bin/rails s -b 0.0.0.0 -p 3000"
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
  test:
    build: .
    container_name: rails-test
    command: bash -c "./bin/rails db:prepare && sleep infinity"
    environment:
      - RAILS_ENV=test
    volumes:
      - .:/rails
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:15
    container_name: rails-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
